# Week1. Homework.

## Author George Chizhmak (17.09.2023).

In [39]:
import pandas as pd
import numpy as np

## Question 1

What's the version of Pandas that you installed?

In [40]:
pd.__version__

'1.5.3'

### Getting the data
For this homework, we'll use the California Housing Prices dataset. Download it from [here](https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv).

### Now read it with Pandas.

In [41]:
data = pd.read_csv("./housing.csv")

## Question 2
How many columns are in the dataset?

In [42]:
data.shape

(20640, 10)

## Question 3
Which columns in the dataset have missing values?

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


## Question 4
How many unique values does the ocean_proximity column have?

In [44]:
len(data['ocean_proximity'].unique())

5

## Question 5
What's the average value of the median_house_value for the houses located near the bay?

In [45]:
data['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [46]:
data.loc[data['ocean_proximity'] == "NEAR BAY", 'median_house_value'].mean()

259212.31179039303

## Question 6

Calculate the average of total_bedrooms column in the dataset.

In [47]:
total_bedrooms_mean = data['total_bedrooms'].mean()
print(total_bedrooms_mean)

537.8705525375618


Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.<br>
Now, calculate the average of total_bedrooms again.<br>
Has it changed?

In [48]:
data['total_bedrooms'].fillna(total_bedrooms_mean).mean()

537.8705525375617

## Question 7
Select all the options located on islands.<br>
Select only columns housing_median_age, total_rooms, total_bedrooms.

In [49]:
island_options = data.loc[data['ocean_proximity'] == "ISLAND", ['housing_median_age', 'total_rooms', 'total_bedrooms']]
island_options

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

Get the underlying NumPy array. Let's call it X.

In [50]:
X = island_options.to_numpy()
print(X)

[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [51]:
XTX = X.T.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

Compute the inverse of XTX.

In [52]:
XTX_INV = np.linalg.inv(XTX)

Create an array y with values [950, 1300, 800, 1000, 1300].

In [53]:
y = np.array([950, 1300, 800, 1000, 1300])

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.<br>
What's the value of the last element of w?

In [54]:
w = (XTX_INV.dot(X.T)).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [55]:
print(w[-1])

5.699229455065586
